import type { Metadata } from "next";

import { site } from "@/content/site";

/**
 * Page metadata in one place, so every page gets a canonical URL and matching
 * Open Graph and X (Twitter) tags. Setting openGraph on a page replaces the
 * root object rather than merging with it, so pages that set only a title
 * would otherwise share the home page's social title.
 */
export function pageMetadata({
  title,
  description,
  path,
  absoluteTitle = false,
}: {
  title: string;
  description: string;
  path: string;
  /** Use the title as given, without the " | Zypa Tech" suffix. */
  absoluteTitle?: boolean;
}): Metadata {
  const fullTitle = absoluteTitle ? title : `${title} | ${site.shortName}`;
  /*
    Listed explicitly: once a page sets openGraph, the card generated by
    app/opengraph-image.tsx is no longer inherited.
  */
  const image = {
    url: "/opengraph-image",
    width: 1200,
    height: 630,
    alt: `${site.name}. ${site.tagline}`,
  };

  return {
    title: absoluteTitle ? { absolute: title } : title,
    description,
    alternates: { canonical: path },
    openGraph: {
      type: "website",
      locale: "en_NG",
      siteName: site.name,
      url: `${site.url}${path === "/" ? "" : path}`,
      title: fullTitle,
      description,
      images: [image],
    },
    twitter: {
      card: "summary_large_image",
      title: fullTitle,
      description,
      images: [image.url],
    },
  };
}
